include: package:lints/core.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: false

linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks
    - unnecessary_const
    - unnecessary_new
